//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Linq.Expressions;
using System.Data.Common;
using DM.Domain;
using DM.Tools;
using DM.Interface;
using DM.Interface.IService;
using DM.Interface.IRepository;

namespace DM.Service.BusinessService
{
    /// <summary>
    /// 业务实现：选项明细表 (Sys_ItemsDetail)
    /// </summary>
    public partial class Sys_ItemsDetailService :ServiceBase<Sys_ItemsDetail>,  ISys_ItemsDetailService,IDependency
    {
       ISys_ItemsDetailRepository m_iRepository=null;
       public Sys_ItemsDetailService(ISys_ItemsDetailRepository iRepository)
            : base(iRepository)  //IOC注入Repository
       {
            m_iRepository=iRepository;
       }
        
    }
}
