//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：用户登录信息表 (Sys_UserLogOn)
    /// </summary>
    [Serializable()]
    public partial class Sys_UserLogOn:BaseModel
    {
	   private string _F_Id;
       /// <summary>
       /// 用户登录主键
       /// </summary>  
       [Key] 
       public string F_Id
	   { 
            get
            {
                BeforeGetProperty("F_Id", _F_Id);
                return _F_Id;
            }
            set
            {
                if(!BeforeSetProperty("F_Id", _F_Id))
                    return;
                _F_Id=value;
                AfterSetProperty("F_Id", _F_Id);
             }
		}
	   private string _F_UserId;
       /// <summary>
       /// 用户主键
       /// </summary>  
        
       public string F_UserId
	   { 
            get
            {
                BeforeGetProperty("F_UserId", _F_UserId);
                return _F_UserId;
            }
            set
            {
                if(!BeforeSetProperty("F_UserId", _F_UserId))
                    return;
                _F_UserId=value;
                AfterSetProperty("F_UserId", _F_UserId);
             }
		}
	   private string _F_UserPassword;
       /// <summary>
       /// 用户密码
       /// </summary>  
        
       public string F_UserPassword
	   { 
            get
            {
                BeforeGetProperty("F_UserPassword", _F_UserPassword);
                return _F_UserPassword;
            }
            set
            {
                if(!BeforeSetProperty("F_UserPassword", _F_UserPassword))
                    return;
                _F_UserPassword=value;
                AfterSetProperty("F_UserPassword", _F_UserPassword);
             }
		}
	   private string _F_UserSecretkey;
       /// <summary>
       /// 用户秘钥
       /// </summary>  
        
       public string F_UserSecretkey
	   { 
            get
            {
                BeforeGetProperty("F_UserSecretkey", _F_UserSecretkey);
                return _F_UserSecretkey;
            }
            set
            {
                if(!BeforeSetProperty("F_UserSecretkey", _F_UserSecretkey))
                    return;
                _F_UserSecretkey=value;
                AfterSetProperty("F_UserSecretkey", _F_UserSecretkey);
             }
		}
	   private DateTime? _F_AllowStartTime;
       /// <summary>
       /// 允许登录时间开始
       /// </summary>  
        
       public DateTime? F_AllowStartTime
	   { 
            get
            {
                BeforeGetProperty("F_AllowStartTime", _F_AllowStartTime);
                return _F_AllowStartTime;
            }
            set
            {
                if(!BeforeSetProperty("F_AllowStartTime", _F_AllowStartTime))
                    return;
                _F_AllowStartTime=value;
                AfterSetProperty("F_AllowStartTime", _F_AllowStartTime);
             }
		}
	   private DateTime? _F_AllowEndTime;
       /// <summary>
       /// 允许登录时间结束
       /// </summary>  
        
       public DateTime? F_AllowEndTime
	   { 
            get
            {
                BeforeGetProperty("F_AllowEndTime", _F_AllowEndTime);
                return _F_AllowEndTime;
            }
            set
            {
                if(!BeforeSetProperty("F_AllowEndTime", _F_AllowEndTime))
                    return;
                _F_AllowEndTime=value;
                AfterSetProperty("F_AllowEndTime", _F_AllowEndTime);
             }
		}
	   private DateTime? _F_LockStartDate;
       /// <summary>
       /// 暂停用户开始日期
       /// </summary>  
        
       public DateTime? F_LockStartDate
	   { 
            get
            {
                BeforeGetProperty("F_LockStartDate", _F_LockStartDate);
                return _F_LockStartDate;
            }
            set
            {
                if(!BeforeSetProperty("F_LockStartDate", _F_LockStartDate))
                    return;
                _F_LockStartDate=value;
                AfterSetProperty("F_LockStartDate", _F_LockStartDate);
             }
		}
	   private DateTime? _F_LockEndDate;
       /// <summary>
       /// 暂停用户结束日期
       /// </summary>  
        
       public DateTime? F_LockEndDate
	   { 
            get
            {
                BeforeGetProperty("F_LockEndDate", _F_LockEndDate);
                return _F_LockEndDate;
            }
            set
            {
                if(!BeforeSetProperty("F_LockEndDate", _F_LockEndDate))
                    return;
                _F_LockEndDate=value;
                AfterSetProperty("F_LockEndDate", _F_LockEndDate);
             }
		}
	   private DateTime? _F_FirstVisitTime;
       /// <summary>
       /// 第一次访问时间
       /// </summary>  
        
       public DateTime? F_FirstVisitTime
	   { 
            get
            {
                BeforeGetProperty("F_FirstVisitTime", _F_FirstVisitTime);
                return _F_FirstVisitTime;
            }
            set
            {
                if(!BeforeSetProperty("F_FirstVisitTime", _F_FirstVisitTime))
                    return;
                _F_FirstVisitTime=value;
                AfterSetProperty("F_FirstVisitTime", _F_FirstVisitTime);
             }
		}
	   private DateTime? _F_PreviousVisitTime;
       /// <summary>
       /// 上一次访问时间
       /// </summary>  
        
       public DateTime? F_PreviousVisitTime
	   { 
            get
            {
                BeforeGetProperty("F_PreviousVisitTime", _F_PreviousVisitTime);
                return _F_PreviousVisitTime;
            }
            set
            {
                if(!BeforeSetProperty("F_PreviousVisitTime", _F_PreviousVisitTime))
                    return;
                _F_PreviousVisitTime=value;
                AfterSetProperty("F_PreviousVisitTime", _F_PreviousVisitTime);
             }
		}
	   private DateTime? _F_LastVisitTime;
       /// <summary>
       /// 最后访问时间
       /// </summary>  
        
       public DateTime? F_LastVisitTime
	   { 
            get
            {
                BeforeGetProperty("F_LastVisitTime", _F_LastVisitTime);
                return _F_LastVisitTime;
            }
            set
            {
                if(!BeforeSetProperty("F_LastVisitTime", _F_LastVisitTime))
                    return;
                _F_LastVisitTime=value;
                AfterSetProperty("F_LastVisitTime", _F_LastVisitTime);
             }
		}
	   private DateTime? _F_ChangePasswordDate;
       /// <summary>
       /// 最后修改密码日期
       /// </summary>  
        
       public DateTime? F_ChangePasswordDate
	   { 
            get
            {
                BeforeGetProperty("F_ChangePasswordDate", _F_ChangePasswordDate);
                return _F_ChangePasswordDate;
            }
            set
            {
                if(!BeforeSetProperty("F_ChangePasswordDate", _F_ChangePasswordDate))
                    return;
                _F_ChangePasswordDate=value;
                AfterSetProperty("F_ChangePasswordDate", _F_ChangePasswordDate);
             }
		}
	   private bool? _F_MultiUserLogin;
       /// <summary>
       /// 允许同时有多用户登录
       /// </summary>  
        
       public bool? F_MultiUserLogin
	   { 
            get
            {
                BeforeGetProperty("F_MultiUserLogin", _F_MultiUserLogin);
                return _F_MultiUserLogin;
            }
            set
            {
                if(!BeforeSetProperty("F_MultiUserLogin", _F_MultiUserLogin))
                    return;
                _F_MultiUserLogin=value;
                AfterSetProperty("F_MultiUserLogin", _F_MultiUserLogin);
             }
		}
	   private int? _F_LogOnCount;
       /// <summary>
       /// 登录次数
       /// </summary>  
        
       public int? F_LogOnCount
	   { 
            get
            {
                BeforeGetProperty("F_LogOnCount", _F_LogOnCount);
                return _F_LogOnCount;
            }
            set
            {
                if(!BeforeSetProperty("F_LogOnCount", _F_LogOnCount))
                    return;
                _F_LogOnCount=value;
                AfterSetProperty("F_LogOnCount", _F_LogOnCount);
             }
		}
	   private bool? _F_UserOnLine;
       /// <summary>
       /// 在线状态
       /// </summary>  
        
       public bool? F_UserOnLine
	   { 
            get
            {
                BeforeGetProperty("F_UserOnLine", _F_UserOnLine);
                return _F_UserOnLine;
            }
            set
            {
                if(!BeforeSetProperty("F_UserOnLine", _F_UserOnLine))
                    return;
                _F_UserOnLine=value;
                AfterSetProperty("F_UserOnLine", _F_UserOnLine);
             }
		}
	   private string _F_Question;
       /// <summary>
       /// 密码提示问题
       /// </summary>  
        
       public string F_Question
	   { 
            get
            {
                BeforeGetProperty("F_Question", _F_Question);
                return _F_Question;
            }
            set
            {
                if(!BeforeSetProperty("F_Question", _F_Question))
                    return;
                _F_Question=value;
                AfterSetProperty("F_Question", _F_Question);
             }
		}
	   private string _F_AnswerQuestion;
       /// <summary>
       /// 密码提示答案
       /// </summary>  
        
       public string F_AnswerQuestion
	   { 
            get
            {
                BeforeGetProperty("F_AnswerQuestion", _F_AnswerQuestion);
                return _F_AnswerQuestion;
            }
            set
            {
                if(!BeforeSetProperty("F_AnswerQuestion", _F_AnswerQuestion))
                    return;
                _F_AnswerQuestion=value;
                AfterSetProperty("F_AnswerQuestion", _F_AnswerQuestion);
             }
		}
	   private bool? _F_CheckIPAddress;
       /// <summary>
       /// 是否访问限制
       /// </summary>  
        
       public bool? F_CheckIPAddress
	   { 
            get
            {
                BeforeGetProperty("F_CheckIPAddress", _F_CheckIPAddress);
                return _F_CheckIPAddress;
            }
            set
            {
                if(!BeforeSetProperty("F_CheckIPAddress", _F_CheckIPAddress))
                    return;
                _F_CheckIPAddress=value;
                AfterSetProperty("F_CheckIPAddress", _F_CheckIPAddress);
             }
		}
	   private string _F_Language;
       /// <summary>
       /// 系统语言
       /// </summary>  
        
       public string F_Language
	   { 
            get
            {
                BeforeGetProperty("F_Language", _F_Language);
                return _F_Language;
            }
            set
            {
                if(!BeforeSetProperty("F_Language", _F_Language))
                    return;
                _F_Language=value;
                AfterSetProperty("F_Language", _F_Language);
             }
		}
	   private string _F_Theme;
       /// <summary>
       /// 系统样式
       /// </summary>  
        
       public string F_Theme
	   { 
            get
            {
                BeforeGetProperty("F_Theme", _F_Theme);
                return _F_Theme;
            }
            set
            {
                if(!BeforeSetProperty("F_Theme", _F_Theme))
                    return;
                _F_Theme=value;
                AfterSetProperty("F_Theme", _F_Theme);
             }
		}
    }
}

