//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：模板夜主页 (Sys_PageIndex)
    /// </summary>
    [Serializable()]
    public partial class Sys_PageIndex:BaseModel
    {
	   private string _F_ID;
       /// <summary>
       /// ID
       /// </summary>  
       [Key] 
       public string F_ID
	   { 
            get
            {
                BeforeGetProperty("F_ID", _F_ID);
                return _F_ID;
            }
            set
            {
                if(!BeforeSetProperty("F_ID", _F_ID))
                    return;
                _F_ID=value;
                AfterSetProperty("F_ID", _F_ID);
             }
		}
	   private string _F_Name;
       /// <summary>
       /// 名称
       /// </summary>  
        
       public string F_Name
	   { 
            get
            {
                BeforeGetProperty("F_Name", _F_Name);
                return _F_Name;
            }
            set
            {
                if(!BeforeSetProperty("F_Name", _F_Name))
                    return;
                _F_Name=value;
                AfterSetProperty("F_Name", _F_Name);
             }
		}
	   private string _F_Type;
       /// <summary>
       /// 样式
       /// </summary>  
        
       public string F_Type
	   { 
            get
            {
                BeforeGetProperty("F_Type", _F_Type);
                return _F_Type;
            }
            set
            {
                if(!BeforeSetProperty("F_Type", _F_Type))
                    return;
                _F_Type=value;
                AfterSetProperty("F_Type", _F_Type);
             }
		}
	   private int _F_TreeTable;
       /// <summary>
       /// 是否树表格
       /// </summary>  
        
       public int F_TreeTable
	   { 
            get
            {
                BeforeGetProperty("F_TreeTable", _F_TreeTable);
                return _F_TreeTable;
            }
            set
            {
                if(!BeforeSetProperty("F_TreeTable", _F_TreeTable))
                    return;
                _F_TreeTable=value;
                AfterSetProperty("F_TreeTable", _F_TreeTable);
             }
		}
	   private string _F_TreeKey;
       /// <summary>
       /// 父节点字段
       /// </summary>  
        
       public string F_TreeKey
	   { 
            get
            {
                BeforeGetProperty("F_TreeKey", _F_TreeKey);
                return _F_TreeKey;
            }
            set
            {
                if(!BeforeSetProperty("F_TreeKey", _F_TreeKey))
                    return;
                _F_TreeKey=value;
                AfterSetProperty("F_TreeKey", _F_TreeKey);
             }
		}
	   private string _F_LeftTreeDataUrl;
       /// <summary>
       /// 左边树数据url
       /// </summary>  
        
       public string F_LeftTreeDataUrl
	   { 
            get
            {
                BeforeGetProperty("F_LeftTreeDataUrl", _F_LeftTreeDataUrl);
                return _F_LeftTreeDataUrl;
            }
            set
            {
                if(!BeforeSetProperty("F_LeftTreeDataUrl", _F_LeftTreeDataUrl))
                    return;
                _F_LeftTreeDataUrl=value;
                AfterSetProperty("F_LeftTreeDataUrl", _F_LeftTreeDataUrl);
             }
		}
	   private string _F_LeftTreeNodeValueToField;
       /// <summary>
       /// 树节点的值对应的主表的那个字段进行筛选（当样式是左树右列表时不允许空）
       /// </summary>  
        
       public string F_LeftTreeNodeValueToField
	   { 
            get
            {
                BeforeGetProperty("F_LeftTreeNodeValueToField", _F_LeftTreeNodeValueToField);
                return _F_LeftTreeNodeValueToField;
            }
            set
            {
                if(!BeforeSetProperty("F_LeftTreeNodeValueToField", _F_LeftTreeNodeValueToField))
                    return;
                _F_LeftTreeNodeValueToField=value;
                AfterSetProperty("F_LeftTreeNodeValueToField", _F_LeftTreeNodeValueToField);
             }
		}
	   private string _F_DataUrl;
       /// <summary>
       /// 获取数据接口
       /// </summary>  
        
       public string F_DataUrl
	   { 
            get
            {
                BeforeGetProperty("F_DataUrl", _F_DataUrl);
                return _F_DataUrl;
            }
            set
            {
                if(!BeforeSetProperty("F_DataUrl", _F_DataUrl))
                    return;
                _F_DataUrl=value;
                AfterSetProperty("F_DataUrl", _F_DataUrl);
             }
		}
	   private string _F_BindTable;
       /// <summary>
       /// 绑定的表
       /// </summary>  
        
       public string F_BindTable
	   { 
            get
            {
                BeforeGetProperty("F_BindTable", _F_BindTable);
                return _F_BindTable;
            }
            set
            {
                if(!BeforeSetProperty("F_BindTable", _F_BindTable))
                    return;
                _F_BindTable=value;
                AfterSetProperty("F_BindTable", _F_BindTable);
             }
		}
	   private string _F_Memo;
       /// <summary>
       /// 描述
       /// </summary>  
        
       public string F_Memo
	   { 
            get
            {
                BeforeGetProperty("F_Memo", _F_Memo);
                return _F_Memo;
            }
            set
            {
                if(!BeforeSetProperty("F_Memo", _F_Memo))
                    return;
                _F_Memo=value;
                AfterSetProperty("F_Memo", _F_Memo);
             }
		}
	   private int _F_Enable;
       /// <summary>
       /// 是否可用
       /// </summary>  
        
       public int F_Enable
	   { 
            get
            {
                BeforeGetProperty("F_Enable", _F_Enable);
                return _F_Enable;
            }
            set
            {
                if(!BeforeSetProperty("F_Enable", _F_Enable))
                    return;
                _F_Enable=value;
                AfterSetProperty("F_Enable", _F_Enable);
             }
		}
	   private string _F_CreatorUserId;
       /// <summary>
       /// 创建人
       /// </summary>  
        
       public string F_CreatorUserId
	   { 
            get
            {
                BeforeGetProperty("F_CreatorUserId", _F_CreatorUserId);
                return _F_CreatorUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorUserId", _F_CreatorUserId))
                    return;
                _F_CreatorUserId=value;
                AfterSetProperty("F_CreatorUserId", _F_CreatorUserId);
             }
		}
	   private DateTime? _F_CreatorTime;
       /// <summary>
       /// 创建时间
       /// </summary>  
        
       public DateTime? F_CreatorTime
	   { 
            get
            {
                BeforeGetProperty("F_CreatorTime", _F_CreatorTime);
                return _F_CreatorTime;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorTime", _F_CreatorTime))
                    return;
                _F_CreatorTime=value;
                AfterSetProperty("F_CreatorTime", _F_CreatorTime);
             }
		}
	   private string _F_LastModifyUserId;
       /// <summary>
       /// 最后修改人
       /// </summary>  
        
       public string F_LastModifyUserId
	   { 
            get
            {
                BeforeGetProperty("F_LastModifyUserId", _F_LastModifyUserId);
                return _F_LastModifyUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_LastModifyUserId", _F_LastModifyUserId))
                    return;
                _F_LastModifyUserId=value;
                AfterSetProperty("F_LastModifyUserId", _F_LastModifyUserId);
             }
		}
	   private DateTime? _F_LastModifyTime;
       /// <summary>
       /// 最后修改时间
       /// </summary>  
        
       public DateTime? F_LastModifyTime
	   { 
            get
            {
                BeforeGetProperty("F_LastModifyTime", _F_LastModifyTime);
                return _F_LastModifyTime;
            }
            set
            {
                if(!BeforeSetProperty("F_LastModifyTime", _F_LastModifyTime))
                    return;
                _F_LastModifyTime=value;
                AfterSetProperty("F_LastModifyTime", _F_LastModifyTime);
             }
		}
	   private string _F_DeleteUserId;
       /// <summary>
       /// 删除人
       /// </summary>  
        
       public string F_DeleteUserId
	   { 
            get
            {
                BeforeGetProperty("F_DeleteUserId", _F_DeleteUserId);
                return _F_DeleteUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteUserId", _F_DeleteUserId))
                    return;
                _F_DeleteUserId=value;
                AfterSetProperty("F_DeleteUserId", _F_DeleteUserId);
             }
		}
	   private DateTime? _F_DeleteTime;
       /// <summary>
       /// 删除时间
       /// </summary>  
        
       public DateTime? F_DeleteTime
	   { 
            get
            {
                BeforeGetProperty("F_DeleteTime", _F_DeleteTime);
                return _F_DeleteTime;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteTime", _F_DeleteTime))
                    return;
                _F_DeleteTime=value;
                AfterSetProperty("F_DeleteTime", _F_DeleteTime);
             }
		}
	   private int _F_DeleteMark;
       /// <summary>
       /// 是否删除
       /// </summary>  
        
       public int F_DeleteMark
	   { 
            get
            {
                BeforeGetProperty("F_DeleteMark", _F_DeleteMark);
                return _F_DeleteMark;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteMark", _F_DeleteMark))
                    return;
                _F_DeleteMark=value;
                AfterSetProperty("F_DeleteMark", _F_DeleteMark);
             }
		}
	   private List<Sys_PageIndexTool> _lstSys_PageIndexTools = new List<Sys_PageIndexTool>();     
       public List<Sys_PageIndexTool> LstSys_PageIndexTools
	   { 
            get
            {
                BeforeGetProperty("LstSys_PageIndexTools",_lstSys_PageIndexTools);
                return _lstSys_PageIndexTools;
            }
            set
            { 
                if(!BeforeSetProperty("LstSys_PageIndexTools",_lstSys_PageIndexTools))
                    return;
                _lstSys_PageIndexTools=value;
                AfterSetProperty("LstSys_PageIndexTools",_lstSys_PageIndexTools);
            }
		}
	   private List<Sys_PageIndexSearch> _lstSys_PageIndexSearchs = new List<Sys_PageIndexSearch>();     
       public List<Sys_PageIndexSearch> LstSys_PageIndexSearchs
	   { 
            get
            {
                BeforeGetProperty("LstSys_PageIndexSearchs",_lstSys_PageIndexSearchs);
                return _lstSys_PageIndexSearchs;
            }
            set
            { 
                if(!BeforeSetProperty("LstSys_PageIndexSearchs",_lstSys_PageIndexSearchs))
                    return;
                _lstSys_PageIndexSearchs=value;
                AfterSetProperty("LstSys_PageIndexSearchs",_lstSys_PageIndexSearchs);
            }
		}
	   private List<Sys_PageIndexTableColumns> _lstSys_PageIndexTableColumnss = new List<Sys_PageIndexTableColumns>();     
       public List<Sys_PageIndexTableColumns> LstSys_PageIndexTableColumnss
	   { 
            get
            {
                BeforeGetProperty("LstSys_PageIndexTableColumnss",_lstSys_PageIndexTableColumnss);
                return _lstSys_PageIndexTableColumnss;
            }
            set
            { 
                if(!BeforeSetProperty("LstSys_PageIndexTableColumnss",_lstSys_PageIndexTableColumnss))
                    return;
                _lstSys_PageIndexTableColumnss=value;
                AfterSetProperty("LstSys_PageIndexTableColumnss",_lstSys_PageIndexTableColumnss);
            }
		}
    }
}

