//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：模块表单实例 (Sys_ModuleFormInstance)
    /// </summary>
    [Serializable()]
    public partial class Sys_ModuleFormInstance:BaseModel
    {
	   private string _F_Id;
       /// <summary>
       /// 表单实例主键
       /// </summary>  
       [Key] 
       public string F_Id
	   { 
            get
            {
                BeforeGetProperty("F_Id", _F_Id);
                return _F_Id;
            }
            set
            {
                if(!BeforeSetProperty("F_Id", _F_Id))
                    return;
                _F_Id=value;
                AfterSetProperty("F_Id", _F_Id);
             }
		}
	   private string _F_FormId;
       /// <summary>
       /// 表单主键
       /// </summary>  
        
       public string F_FormId
	   { 
            get
            {
                BeforeGetProperty("F_FormId", _F_FormId);
                return _F_FormId;
            }
            set
            {
                if(!BeforeSetProperty("F_FormId", _F_FormId))
                    return;
                _F_FormId=value;
                AfterSetProperty("F_FormId", _F_FormId);
             }
		}
	   private string _F_ObjectId;
       /// <summary>
       /// 对象主键
       /// </summary>  
        
       public string F_ObjectId
	   { 
            get
            {
                BeforeGetProperty("F_ObjectId", _F_ObjectId);
                return _F_ObjectId;
            }
            set
            {
                if(!BeforeSetProperty("F_ObjectId", _F_ObjectId))
                    return;
                _F_ObjectId=value;
                AfterSetProperty("F_ObjectId", _F_ObjectId);
             }
		}
	   private string _F_InstanceJson;
       /// <summary>
       /// 表单实例Json
       /// </summary>  
        
       public string F_InstanceJson
	   { 
            get
            {
                BeforeGetProperty("F_InstanceJson", _F_InstanceJson);
                return _F_InstanceJson;
            }
            set
            {
                if(!BeforeSetProperty("F_InstanceJson", _F_InstanceJson))
                    return;
                _F_InstanceJson=value;
                AfterSetProperty("F_InstanceJson", _F_InstanceJson);
             }
		}
	   private int? _F_SortCode;
       /// <summary>
       /// 排序码
       /// </summary>  
        
       public int? F_SortCode
	   { 
            get
            {
                BeforeGetProperty("F_SortCode", _F_SortCode);
                return _F_SortCode;
            }
            set
            {
                if(!BeforeSetProperty("F_SortCode", _F_SortCode))
                    return;
                _F_SortCode=value;
                AfterSetProperty("F_SortCode", _F_SortCode);
             }
		}
	   private DateTime? _F_CreatorTime;
       /// <summary>
       /// 创建时间
       /// </summary>  
        
       public DateTime? F_CreatorTime
	   { 
            get
            {
                BeforeGetProperty("F_CreatorTime", _F_CreatorTime);
                return _F_CreatorTime;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorTime", _F_CreatorTime))
                    return;
                _F_CreatorTime=value;
                AfterSetProperty("F_CreatorTime", _F_CreatorTime);
             }
		}
	   private string _F_CreatorUserId;
       /// <summary>
       /// 创建用户
       /// </summary>  
        
       public string F_CreatorUserId
	   { 
            get
            {
                BeforeGetProperty("F_CreatorUserId", _F_CreatorUserId);
                return _F_CreatorUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorUserId", _F_CreatorUserId))
                    return;
                _F_CreatorUserId=value;
                AfterSetProperty("F_CreatorUserId", _F_CreatorUserId);
             }
		}
    }
}

