//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：主页表格字段设置 (Sys_PageIndexTableColumns)
    /// </summary>
    [Serializable()]
    public partial class Sys_PageIndexTableColumns:BaseModel
    {
	   private string _F_ID;
       /// <summary>
       /// F_ID
       /// </summary>  
       [Key] 
       public string F_ID
	   { 
            get
            {
                BeforeGetProperty("F_ID", _F_ID);
                return _F_ID;
            }
            set
            {
                if(!BeforeSetProperty("F_ID", _F_ID))
                    return;
                _F_ID=value;
                AfterSetProperty("F_ID", _F_ID);
             }
		}
	   private string _F_PageIndexF_ID;
       /// <summary>
       /// 表头ID
       /// </summary>  
        
       public string F_PageIndexF_ID
	   { 
            get
            {
                BeforeGetProperty("F_PageIndexF_ID", _F_PageIndexF_ID);
                return _F_PageIndexF_ID;
            }
            set
            {
                if(!BeforeSetProperty("F_PageIndexF_ID", _F_PageIndexF_ID))
                    return;
                _F_PageIndexF_ID=value;
                AfterSetProperty("F_PageIndexF_ID", _F_PageIndexF_ID);
             }
		}
	   private string _F_Field;
       /// <summary>
       /// 字段
       /// </summary>  
        
       public string F_Field
	   { 
            get
            {
                BeforeGetProperty("F_Field", _F_Field);
                return _F_Field;
            }
            set
            {
                if(!BeforeSetProperty("F_Field", _F_Field))
                    return;
                _F_Field=value;
                AfterSetProperty("F_Field", _F_Field);
             }
		}
	   private string _F_FieldName;
       /// <summary>
       /// 字段显示名
       /// </summary>  
        
       public string F_FieldName
	   { 
            get
            {
                BeforeGetProperty("F_FieldName", _F_FieldName);
                return _F_FieldName;
            }
            set
            {
                if(!BeforeSetProperty("F_FieldName", _F_FieldName))
                    return;
                _F_FieldName=value;
                AfterSetProperty("F_FieldName", _F_FieldName);
             }
		}
	   private int _F_IsKey;
       /// <summary>
       /// 是否主键
       /// </summary>  
        
       public int F_IsKey
	   { 
            get
            {
                BeforeGetProperty("F_IsKey", _F_IsKey);
                return _F_IsKey;
            }
            set
            {
                if(!BeforeSetProperty("F_IsKey", _F_IsKey))
                    return;
                _F_IsKey=value;
                AfterSetProperty("F_IsKey", _F_IsKey);
             }
		}
	   private int _F_IsHidden;
       /// <summary>
       /// 是否隐藏
       /// </summary>  
        
       public int F_IsHidden
	   { 
            get
            {
                BeforeGetProperty("F_IsHidden", _F_IsHidden);
                return _F_IsHidden;
            }
            set
            {
                if(!BeforeSetProperty("F_IsHidden", _F_IsHidden))
                    return;
                _F_IsHidden=value;
                AfterSetProperty("F_IsHidden", _F_IsHidden);
             }
		}
	   private int _F_Width;
       /// <summary>
       /// 列宽度
       /// </summary>  
        
       public int F_Width
	   { 
            get
            {
                BeforeGetProperty("F_Width", _F_Width);
                return _F_Width;
            }
            set
            {
                if(!BeforeSetProperty("F_Width", _F_Width))
                    return;
                _F_Width=value;
                AfterSetProperty("F_Width", _F_Width);
             }
		}
	   private string _F_Aligh;
       /// <summary>
       /// 文字对齐方式
       /// </summary>  
        
       public string F_Aligh
	   { 
            get
            {
                BeforeGetProperty("F_Aligh", _F_Aligh);
                return _F_Aligh;
            }
            set
            {
                if(!BeforeSetProperty("F_Aligh", _F_Aligh))
                    return;
                _F_Aligh=value;
                AfterSetProperty("F_Aligh", _F_Aligh);
             }
		}
	   private string _F_FormatterType;
       /// <summary>
       /// 格式化类型
       /// </summary>  
        
       public string F_FormatterType
	   { 
            get
            {
                BeforeGetProperty("F_FormatterType", _F_FormatterType);
                return _F_FormatterType;
            }
            set
            {
                if(!BeforeSetProperty("F_FormatterType", _F_FormatterType))
                    return;
                _F_FormatterType=value;
                AfterSetProperty("F_FormatterType", _F_FormatterType);
             }
		}
	   private string _F_Formatter;
       /// <summary>
       /// 格式化Js代码
       /// </summary>  
        
       public string F_Formatter
	   { 
            get
            {
                BeforeGetProperty("F_Formatter", _F_Formatter);
                return _F_Formatter;
            }
            set
            {
                if(!BeforeSetProperty("F_Formatter", _F_Formatter))
                    return;
                _F_Formatter=value;
                AfterSetProperty("F_Formatter", _F_Formatter);
             }
		}
	   private string _F_FormatterForDate;
       /// <summary>
       /// 时间格式化字符串
       /// </summary>  
        
       public string F_FormatterForDate
	   { 
            get
            {
                BeforeGetProperty("F_FormatterForDate", _F_FormatterForDate);
                return _F_FormatterForDate;
            }
            set
            {
                if(!BeforeSetProperty("F_FormatterForDate", _F_FormatterForDate))
                    return;
                _F_FormatterForDate=value;
                AfterSetProperty("F_FormatterForDate", _F_FormatterForDate);
             }
		}
	   private string _F_FormatterForDic;
       /// <summary>
       /// 字典id
       /// </summary>  
        
       public string F_FormatterForDic
	   { 
            get
            {
                BeforeGetProperty("F_FormatterForDic", _F_FormatterForDic);
                return _F_FormatterForDic;
            }
            set
            {
                if(!BeforeSetProperty("F_FormatterForDic", _F_FormatterForDic))
                    return;
                _F_FormatterForDic=value;
                AfterSetProperty("F_FormatterForDic", _F_FormatterForDic);
             }
		}
	   private int _F_Sort;
       /// <summary>
       /// 排序
       /// </summary>  
        
       public int F_Sort
	   { 
            get
            {
                BeforeGetProperty("F_Sort", _F_Sort);
                return _F_Sort;
            }
            set
            {
                if(!BeforeSetProperty("F_Sort", _F_Sort))
                    return;
                _F_Sort=value;
                AfterSetProperty("F_Sort", _F_Sort);
             }
		}
	   private string _F_Memo;
       /// <summary>
       /// 描述
       /// </summary>  
        
       public string F_Memo
	   { 
            get
            {
                BeforeGetProperty("F_Memo", _F_Memo);
                return _F_Memo;
            }
            set
            {
                if(!BeforeSetProperty("F_Memo", _F_Memo))
                    return;
                _F_Memo=value;
                AfterSetProperty("F_Memo", _F_Memo);
             }
		}
	   private int _F_Enable;
       /// <summary>
       /// 是否可用
       /// </summary>  
        
       public int F_Enable
	   { 
            get
            {
                BeforeGetProperty("F_Enable", _F_Enable);
                return _F_Enable;
            }
            set
            {
                if(!BeforeSetProperty("F_Enable", _F_Enable))
                    return;
                _F_Enable=value;
                AfterSetProperty("F_Enable", _F_Enable);
             }
		}
	  
	   private Sys_PageIndex _Sys_PageIndex ;    
       [ForeignKey("F_PageIndexF_ID")] 
       public Sys_PageIndex Sys_PageIndex
	   { 
            get
            {
                BeforeGetProperty("Sys_PageIndex",_Sys_PageIndex );
                return _Sys_PageIndex;
            }
            set
            {
                if(!BeforeSetProperty("Sys_PageIndex",_Sys_PageIndex))
                    return;
                _Sys_PageIndex=value;
                AfterSetProperty("Sys_PageIndex",_Sys_PageIndex);
            }
		}
    }
}

