//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：组织表 (Sys_Organize)
    /// </summary>
    [Serializable()]
    public partial class Sys_Organize:BaseModel
    {
	   private string _F_Id;
       /// <summary>
       /// 组织主键
       /// </summary>  
       [Key] 
       public string F_Id
	   { 
            get
            {
                BeforeGetProperty("F_Id", _F_Id);
                return _F_Id;
            }
            set
            {
                if(!BeforeSetProperty("F_Id", _F_Id))
                    return;
                _F_Id=value;
                AfterSetProperty("F_Id", _F_Id);
             }
		}
	   private string _F_ParentId;
       /// <summary>
       /// 父级
       /// </summary>  
        
       public string F_ParentId
	   { 
            get
            {
                BeforeGetProperty("F_ParentId", _F_ParentId);
                return _F_ParentId;
            }
            set
            {
                if(!BeforeSetProperty("F_ParentId", _F_ParentId))
                    return;
                _F_ParentId=value;
                AfterSetProperty("F_ParentId", _F_ParentId);
             }
		}
	   private int? _F_Layers;
       /// <summary>
       /// 层次
       /// </summary>  
        
       public int? F_Layers
	   { 
            get
            {
                BeforeGetProperty("F_Layers", _F_Layers);
                return _F_Layers;
            }
            set
            {
                if(!BeforeSetProperty("F_Layers", _F_Layers))
                    return;
                _F_Layers=value;
                AfterSetProperty("F_Layers", _F_Layers);
             }
		}
	   private string _F_EnCode;
       /// <summary>
       /// 编码
       /// </summary>  
        
       public string F_EnCode
	   { 
            get
            {
                BeforeGetProperty("F_EnCode", _F_EnCode);
                return _F_EnCode;
            }
            set
            {
                if(!BeforeSetProperty("F_EnCode", _F_EnCode))
                    return;
                _F_EnCode=value;
                AfterSetProperty("F_EnCode", _F_EnCode);
             }
		}
	   private string _F_FullName;
       /// <summary>
       /// 名称
       /// </summary>  
        
       public string F_FullName
	   { 
            get
            {
                BeforeGetProperty("F_FullName", _F_FullName);
                return _F_FullName;
            }
            set
            {
                if(!BeforeSetProperty("F_FullName", _F_FullName))
                    return;
                _F_FullName=value;
                AfterSetProperty("F_FullName", _F_FullName);
             }
		}
	   private string _F_ShortName;
       /// <summary>
       /// 简称
       /// </summary>  
        
       public string F_ShortName
	   { 
            get
            {
                BeforeGetProperty("F_ShortName", _F_ShortName);
                return _F_ShortName;
            }
            set
            {
                if(!BeforeSetProperty("F_ShortName", _F_ShortName))
                    return;
                _F_ShortName=value;
                AfterSetProperty("F_ShortName", _F_ShortName);
             }
		}
	   private string _F_CategoryId;
       /// <summary>
       /// 分类
       /// </summary>  
        
       public string F_CategoryId
	   { 
            get
            {
                BeforeGetProperty("F_CategoryId", _F_CategoryId);
                return _F_CategoryId;
            }
            set
            {
                if(!BeforeSetProperty("F_CategoryId", _F_CategoryId))
                    return;
                _F_CategoryId=value;
                AfterSetProperty("F_CategoryId", _F_CategoryId);
             }
		}
	   private string _F_ManagerId;
       /// <summary>
       /// 负责人
       /// </summary>  
        
       public string F_ManagerId
	   { 
            get
            {
                BeforeGetProperty("F_ManagerId", _F_ManagerId);
                return _F_ManagerId;
            }
            set
            {
                if(!BeforeSetProperty("F_ManagerId", _F_ManagerId))
                    return;
                _F_ManagerId=value;
                AfterSetProperty("F_ManagerId", _F_ManagerId);
             }
		}
	   private string _F_TelePhone;
       /// <summary>
       /// 电话
       /// </summary>  
        
       public string F_TelePhone
	   { 
            get
            {
                BeforeGetProperty("F_TelePhone", _F_TelePhone);
                return _F_TelePhone;
            }
            set
            {
                if(!BeforeSetProperty("F_TelePhone", _F_TelePhone))
                    return;
                _F_TelePhone=value;
                AfterSetProperty("F_TelePhone", _F_TelePhone);
             }
		}
	   private string _F_MobilePhone;
       /// <summary>
       /// 手机
       /// </summary>  
        
       public string F_MobilePhone
	   { 
            get
            {
                BeforeGetProperty("F_MobilePhone", _F_MobilePhone);
                return _F_MobilePhone;
            }
            set
            {
                if(!BeforeSetProperty("F_MobilePhone", _F_MobilePhone))
                    return;
                _F_MobilePhone=value;
                AfterSetProperty("F_MobilePhone", _F_MobilePhone);
             }
		}
	   private string _F_WeChat;
       /// <summary>
       /// 微信
       /// </summary>  
        
       public string F_WeChat
	   { 
            get
            {
                BeforeGetProperty("F_WeChat", _F_WeChat);
                return _F_WeChat;
            }
            set
            {
                if(!BeforeSetProperty("F_WeChat", _F_WeChat))
                    return;
                _F_WeChat=value;
                AfterSetProperty("F_WeChat", _F_WeChat);
             }
		}
	   private string _F_Fax;
       /// <summary>
       /// 传真
       /// </summary>  
        
       public string F_Fax
	   { 
            get
            {
                BeforeGetProperty("F_Fax", _F_Fax);
                return _F_Fax;
            }
            set
            {
                if(!BeforeSetProperty("F_Fax", _F_Fax))
                    return;
                _F_Fax=value;
                AfterSetProperty("F_Fax", _F_Fax);
             }
		}
	   private string _F_Email;
       /// <summary>
       /// 邮箱
       /// </summary>  
        
       public string F_Email
	   { 
            get
            {
                BeforeGetProperty("F_Email", _F_Email);
                return _F_Email;
            }
            set
            {
                if(!BeforeSetProperty("F_Email", _F_Email))
                    return;
                _F_Email=value;
                AfterSetProperty("F_Email", _F_Email);
             }
		}
	   private string _F_AreaId;
       /// <summary>
       /// 归属区域
       /// </summary>  
        
       public string F_AreaId
	   { 
            get
            {
                BeforeGetProperty("F_AreaId", _F_AreaId);
                return _F_AreaId;
            }
            set
            {
                if(!BeforeSetProperty("F_AreaId", _F_AreaId))
                    return;
                _F_AreaId=value;
                AfterSetProperty("F_AreaId", _F_AreaId);
             }
		}
	   private string _F_Address;
       /// <summary>
       /// 联系地址
       /// </summary>  
        
       public string F_Address
	   { 
            get
            {
                BeforeGetProperty("F_Address", _F_Address);
                return _F_Address;
            }
            set
            {
                if(!BeforeSetProperty("F_Address", _F_Address))
                    return;
                _F_Address=value;
                AfterSetProperty("F_Address", _F_Address);
             }
		}
	   private bool? _F_AllowEdit;
       /// <summary>
       /// 允许编辑
       /// </summary>  
        
       public bool? F_AllowEdit
	   { 
            get
            {
                BeforeGetProperty("F_AllowEdit", _F_AllowEdit);
                return _F_AllowEdit;
            }
            set
            {
                if(!BeforeSetProperty("F_AllowEdit", _F_AllowEdit))
                    return;
                _F_AllowEdit=value;
                AfterSetProperty("F_AllowEdit", _F_AllowEdit);
             }
		}
	   private bool? _F_AllowDelete;
       /// <summary>
       /// 允许删除
       /// </summary>  
        
       public bool? F_AllowDelete
	   { 
            get
            {
                BeforeGetProperty("F_AllowDelete", _F_AllowDelete);
                return _F_AllowDelete;
            }
            set
            {
                if(!BeforeSetProperty("F_AllowDelete", _F_AllowDelete))
                    return;
                _F_AllowDelete=value;
                AfterSetProperty("F_AllowDelete", _F_AllowDelete);
             }
		}
	   private int? _F_SortCode;
       /// <summary>
       /// 排序码
       /// </summary>  
        
       public int? F_SortCode
	   { 
            get
            {
                BeforeGetProperty("F_SortCode", _F_SortCode);
                return _F_SortCode;
            }
            set
            {
                if(!BeforeSetProperty("F_SortCode", _F_SortCode))
                    return;
                _F_SortCode=value;
                AfterSetProperty("F_SortCode", _F_SortCode);
             }
		}
	   private bool? _F_DeleteMark;
       /// <summary>
       /// 删除标志
       /// </summary>  
        
       public bool? F_DeleteMark
	   { 
            get
            {
                BeforeGetProperty("F_DeleteMark", _F_DeleteMark);
                return _F_DeleteMark;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteMark", _F_DeleteMark))
                    return;
                _F_DeleteMark=value;
                AfterSetProperty("F_DeleteMark", _F_DeleteMark);
             }
		}
	   private bool? _F_EnabledMark;
       /// <summary>
       /// 有效标志
       /// </summary>  
        
       public bool? F_EnabledMark
	   { 
            get
            {
                BeforeGetProperty("F_EnabledMark", _F_EnabledMark);
                return _F_EnabledMark;
            }
            set
            {
                if(!BeforeSetProperty("F_EnabledMark", _F_EnabledMark))
                    return;
                _F_EnabledMark=value;
                AfterSetProperty("F_EnabledMark", _F_EnabledMark);
             }
		}
	   private string _F_Description;
       /// <summary>
       /// 描述
       /// </summary>  
        
       public string F_Description
	   { 
            get
            {
                BeforeGetProperty("F_Description", _F_Description);
                return _F_Description;
            }
            set
            {
                if(!BeforeSetProperty("F_Description", _F_Description))
                    return;
                _F_Description=value;
                AfterSetProperty("F_Description", _F_Description);
             }
		}
	   private DateTime? _F_CreatorTime;
       /// <summary>
       /// 创建时间
       /// </summary>  
        
       public DateTime? F_CreatorTime
	   { 
            get
            {
                BeforeGetProperty("F_CreatorTime", _F_CreatorTime);
                return _F_CreatorTime;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorTime", _F_CreatorTime))
                    return;
                _F_CreatorTime=value;
                AfterSetProperty("F_CreatorTime", _F_CreatorTime);
             }
		}
	   private string _F_CreatorUserId;
       /// <summary>
       /// 创建用户
       /// </summary>  
        
       public string F_CreatorUserId
	   { 
            get
            {
                BeforeGetProperty("F_CreatorUserId", _F_CreatorUserId);
                return _F_CreatorUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorUserId", _F_CreatorUserId))
                    return;
                _F_CreatorUserId=value;
                AfterSetProperty("F_CreatorUserId", _F_CreatorUserId);
             }
		}
	   private DateTime? _F_LastModifyTime;
       /// <summary>
       /// 最后修改时间
       /// </summary>  
        
       public DateTime? F_LastModifyTime
	   { 
            get
            {
                BeforeGetProperty("F_LastModifyTime", _F_LastModifyTime);
                return _F_LastModifyTime;
            }
            set
            {
                if(!BeforeSetProperty("F_LastModifyTime", _F_LastModifyTime))
                    return;
                _F_LastModifyTime=value;
                AfterSetProperty("F_LastModifyTime", _F_LastModifyTime);
             }
		}
	   private string _F_LastModifyUserId;
       /// <summary>
       /// 最后修改用户
       /// </summary>  
        
       public string F_LastModifyUserId
	   { 
            get
            {
                BeforeGetProperty("F_LastModifyUserId", _F_LastModifyUserId);
                return _F_LastModifyUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_LastModifyUserId", _F_LastModifyUserId))
                    return;
                _F_LastModifyUserId=value;
                AfterSetProperty("F_LastModifyUserId", _F_LastModifyUserId);
             }
		}
	   private DateTime? _F_DeleteTime;
       /// <summary>
       /// 删除时间
       /// </summary>  
        
       public DateTime? F_DeleteTime
	   { 
            get
            {
                BeforeGetProperty("F_DeleteTime", _F_DeleteTime);
                return _F_DeleteTime;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteTime", _F_DeleteTime))
                    return;
                _F_DeleteTime=value;
                AfterSetProperty("F_DeleteTime", _F_DeleteTime);
             }
		}
	   private string _F_DeleteUserId;
       /// <summary>
       /// 删除用户
       /// </summary>  
        
       public string F_DeleteUserId
	   { 
            get
            {
                BeforeGetProperty("F_DeleteUserId", _F_DeleteUserId);
                return _F_DeleteUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteUserId", _F_DeleteUserId))
                    return;
                _F_DeleteUserId=value;
                AfterSetProperty("F_DeleteUserId", _F_DeleteUserId);
             }
		}
    }
}

