//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：数据库备份 (Sys_DbBackup)
    /// </summary>
    [Serializable()]
    public partial class Sys_DbBackup:BaseModel
    {
	   private string _F_Id;
       /// <summary>
       /// 备份主键
       /// </summary>  
       [Key] 
       public string F_Id
	   { 
            get
            {
                BeforeGetProperty("F_Id", _F_Id);
                return _F_Id;
            }
            set
            {
                if(!BeforeSetProperty("F_Id", _F_Id))
                    return;
                _F_Id=value;
                AfterSetProperty("F_Id", _F_Id);
             }
		}
	   private string _F_BackupType;
       /// <summary>
       /// 备份类型
       /// </summary>  
        
       public string F_BackupType
	   { 
            get
            {
                BeforeGetProperty("F_BackupType", _F_BackupType);
                return _F_BackupType;
            }
            set
            {
                if(!BeforeSetProperty("F_BackupType", _F_BackupType))
                    return;
                _F_BackupType=value;
                AfterSetProperty("F_BackupType", _F_BackupType);
             }
		}
	   private string _F_DbName;
       /// <summary>
       /// 数据库名称
       /// </summary>  
        
       public string F_DbName
	   { 
            get
            {
                BeforeGetProperty("F_DbName", _F_DbName);
                return _F_DbName;
            }
            set
            {
                if(!BeforeSetProperty("F_DbName", _F_DbName))
                    return;
                _F_DbName=value;
                AfterSetProperty("F_DbName", _F_DbName);
             }
		}
	   private string _F_FileName;
       /// <summary>
       /// 文件名称
       /// </summary>  
        
       public string F_FileName
	   { 
            get
            {
                BeforeGetProperty("F_FileName", _F_FileName);
                return _F_FileName;
            }
            set
            {
                if(!BeforeSetProperty("F_FileName", _F_FileName))
                    return;
                _F_FileName=value;
                AfterSetProperty("F_FileName", _F_FileName);
             }
		}
	   private string _F_FileSize;
       /// <summary>
       /// 文件大小
       /// </summary>  
        
       public string F_FileSize
	   { 
            get
            {
                BeforeGetProperty("F_FileSize", _F_FileSize);
                return _F_FileSize;
            }
            set
            {
                if(!BeforeSetProperty("F_FileSize", _F_FileSize))
                    return;
                _F_FileSize=value;
                AfterSetProperty("F_FileSize", _F_FileSize);
             }
		}
	   private string _F_FilePath;
       /// <summary>
       /// 文件路径
       /// </summary>  
        
       public string F_FilePath
	   { 
            get
            {
                BeforeGetProperty("F_FilePath", _F_FilePath);
                return _F_FilePath;
            }
            set
            {
                if(!BeforeSetProperty("F_FilePath", _F_FilePath))
                    return;
                _F_FilePath=value;
                AfterSetProperty("F_FilePath", _F_FilePath);
             }
		}
	   private DateTime? _F_BackupTime;
       /// <summary>
       /// 备份时间
       /// </summary>  
        
       public DateTime? F_BackupTime
	   { 
            get
            {
                BeforeGetProperty("F_BackupTime", _F_BackupTime);
                return _F_BackupTime;
            }
            set
            {
                if(!BeforeSetProperty("F_BackupTime", _F_BackupTime))
                    return;
                _F_BackupTime=value;
                AfterSetProperty("F_BackupTime", _F_BackupTime);
             }
		}
	   private int? _F_SortCode;
       /// <summary>
       /// 排序码
       /// </summary>  
        
       public int? F_SortCode
	   { 
            get
            {
                BeforeGetProperty("F_SortCode", _F_SortCode);
                return _F_SortCode;
            }
            set
            {
                if(!BeforeSetProperty("F_SortCode", _F_SortCode))
                    return;
                _F_SortCode=value;
                AfterSetProperty("F_SortCode", _F_SortCode);
             }
		}
	   private bool? _F_DeleteMark;
       /// <summary>
       /// 删除标志
       /// </summary>  
        
       public bool? F_DeleteMark
	   { 
            get
            {
                BeforeGetProperty("F_DeleteMark", _F_DeleteMark);
                return _F_DeleteMark;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteMark", _F_DeleteMark))
                    return;
                _F_DeleteMark=value;
                AfterSetProperty("F_DeleteMark", _F_DeleteMark);
             }
		}
	   private bool? _F_EnabledMark;
       /// <summary>
       /// 有效标志
       /// </summary>  
        
       public bool? F_EnabledMark
	   { 
            get
            {
                BeforeGetProperty("F_EnabledMark", _F_EnabledMark);
                return _F_EnabledMark;
            }
            set
            {
                if(!BeforeSetProperty("F_EnabledMark", _F_EnabledMark))
                    return;
                _F_EnabledMark=value;
                AfterSetProperty("F_EnabledMark", _F_EnabledMark);
             }
		}
	   private string _F_Description;
       /// <summary>
       /// 描述
       /// </summary>  
        
       public string F_Description
	   { 
            get
            {
                BeforeGetProperty("F_Description", _F_Description);
                return _F_Description;
            }
            set
            {
                if(!BeforeSetProperty("F_Description", _F_Description))
                    return;
                _F_Description=value;
                AfterSetProperty("F_Description", _F_Description);
             }
		}
	   private DateTime? _F_CreatorTime;
       /// <summary>
       /// 创建时间
       /// </summary>  
        
       public DateTime? F_CreatorTime
	   { 
            get
            {
                BeforeGetProperty("F_CreatorTime", _F_CreatorTime);
                return _F_CreatorTime;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorTime", _F_CreatorTime))
                    return;
                _F_CreatorTime=value;
                AfterSetProperty("F_CreatorTime", _F_CreatorTime);
             }
		}
	   private string _F_CreatorUserId;
       /// <summary>
       /// 创建用户
       /// </summary>  
        
       public string F_CreatorUserId
	   { 
            get
            {
                BeforeGetProperty("F_CreatorUserId", _F_CreatorUserId);
                return _F_CreatorUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_CreatorUserId", _F_CreatorUserId))
                    return;
                _F_CreatorUserId=value;
                AfterSetProperty("F_CreatorUserId", _F_CreatorUserId);
             }
		}
	   private DateTime? _F_LastModifyTime;
       /// <summary>
       /// 最后修改时间
       /// </summary>  
        
       public DateTime? F_LastModifyTime
	   { 
            get
            {
                BeforeGetProperty("F_LastModifyTime", _F_LastModifyTime);
                return _F_LastModifyTime;
            }
            set
            {
                if(!BeforeSetProperty("F_LastModifyTime", _F_LastModifyTime))
                    return;
                _F_LastModifyTime=value;
                AfterSetProperty("F_LastModifyTime", _F_LastModifyTime);
             }
		}
	   private string _F_LastModifyUserId;
       /// <summary>
       /// 最后修改用户
       /// </summary>  
        
       public string F_LastModifyUserId
	   { 
            get
            {
                BeforeGetProperty("F_LastModifyUserId", _F_LastModifyUserId);
                return _F_LastModifyUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_LastModifyUserId", _F_LastModifyUserId))
                    return;
                _F_LastModifyUserId=value;
                AfterSetProperty("F_LastModifyUserId", _F_LastModifyUserId);
             }
		}
	   private DateTime? _F_DeleteTime;
       /// <summary>
       /// 删除时间
       /// </summary>  
        
       public DateTime? F_DeleteTime
	   { 
            get
            {
                BeforeGetProperty("F_DeleteTime", _F_DeleteTime);
                return _F_DeleteTime;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteTime", _F_DeleteTime))
                    return;
                _F_DeleteTime=value;
                AfterSetProperty("F_DeleteTime", _F_DeleteTime);
             }
		}
	   private string _F_DeleteUserId;
       /// <summary>
       /// 删除用户
       /// </summary>  
        
       public string F_DeleteUserId
	   { 
            get
            {
                BeforeGetProperty("F_DeleteUserId", _F_DeleteUserId);
                return _F_DeleteUserId;
            }
            set
            {
                if(!BeforeSetProperty("F_DeleteUserId", _F_DeleteUserId))
                    return;
                _F_DeleteUserId=value;
                AfterSetProperty("F_DeleteUserId", _F_DeleteUserId);
             }
		}
    }
}

