//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类： (Sys_Test)
    /// </summary>
    [Serializable()]
    public partial class Sys_Test:BaseModel
    {
	   private int _ID;
       /// <summary>
       /// ID
       /// </summary>  
       [Key] 
       public int ID
	   { 
            get{
                    BeforeGetProperty("ID", _ID);
                    return _ID;
                }
            set{
                    if(!BeforeSetProperty("ID", _ID))
                        return;
                     _ID=value;
                    AfterSetProperty("ID", _ID);
                }
		}
	   private int _Sys_UserID;
       /// <summary>
       /// Sys_UserID
       /// </summary>  
        
       public int Sys_UserID
	   { 
            get{
                    BeforeGetProperty("Sys_UserID", _Sys_UserID);
                    return _Sys_UserID;
                }
            set{
                    if(!BeforeSetProperty("Sys_UserID", _Sys_UserID))
                        return;
                     _Sys_UserID=value;
                    AfterSetProperty("Sys_UserID", _Sys_UserID);
                }
		}
	   private string _TestName;
       /// <summary>
       /// TestName
       /// </summary>  
        
       public string TestName
	   { 
            get{
                    BeforeGetProperty("TestName", _TestName);
                    return _TestName;
                }
            set{
                    if(!BeforeSetProperty("TestName", _TestName))
                        return;
                     _TestName=value;
                    AfterSetProperty("TestName", _TestName);
                }
		}
	  
	   private Sys_User _Sys_User ;    
       [ForeignKey(" Sys_UserID")] 
       public Sys_User Sys_User
	   { 
            get
            {
                BeforeGetProperty("Sys_User",_Sys_User );
                return _Sys_User;
            }
            set
            {
                if(!BeforeSetProperty("Sys_User",_Sys_User))
                    return;
                _Sys_User=value;
                AfterSetProperty("Sys_User",_Sys_User);
            }
		}
    }
}

