//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类：工具栏设置 (Sys_PageIndexTool)
    /// </summary>
    [Serializable()]
    public partial class Sys_PageIndexTool:BaseModel
    {
	   private string _F_ID;
       /// <summary>
       /// F_ID
       /// </summary>  
       [Key] 
       public string F_ID
	   { 
            get
            {
                BeforeGetProperty("F_ID", _F_ID);
                return _F_ID;
            }
            set
            {
                if(!BeforeSetProperty("F_ID", _F_ID))
                    return;
                _F_ID=value;
                AfterSetProperty("F_ID", _F_ID);
             }
		}
	   private string _F_PageIndexF_ID;
       /// <summary>
       /// 表头ID
       /// </summary>  
        
       public string F_PageIndexF_ID
	   { 
            get
            {
                BeforeGetProperty("F_PageIndexF_ID", _F_PageIndexF_ID);
                return _F_PageIndexF_ID;
            }
            set
            {
                if(!BeforeSetProperty("F_PageIndexF_ID", _F_PageIndexF_ID))
                    return;
                _F_PageIndexF_ID=value;
                AfterSetProperty("F_PageIndexF_ID", _F_PageIndexF_ID);
             }
		}
	   private string _F_Name;
       /// <summary>
       /// 名称
       /// </summary>  
        
       public string F_Name
	   { 
            get
            {
                BeforeGetProperty("F_Name", _F_Name);
                return _F_Name;
            }
            set
            {
                if(!BeforeSetProperty("F_Name", _F_Name))
                    return;
                _F_Name=value;
                AfterSetProperty("F_Name", _F_Name);
             }
		}
	   private string _F_Icon;
       /// <summary>
       /// 按钮图标
       /// </summary>  
        
       public string F_Icon
	   { 
            get
            {
                BeforeGetProperty("F_Icon", _F_Icon);
                return _F_Icon;
            }
            set
            {
                if(!BeforeSetProperty("F_Icon", _F_Icon))
                    return;
                _F_Icon=value;
                AfterSetProperty("F_Icon", _F_Icon);
             }
		}
	   private string _F_ClickEvent;
       /// <summary>
       /// 点击执行事件
       /// </summary>  
        
       public string F_ClickEvent
	   { 
            get
            {
                BeforeGetProperty("F_ClickEvent", _F_ClickEvent);
                return _F_ClickEvent;
            }
            set
            {
                if(!BeforeSetProperty("F_ClickEvent", _F_ClickEvent))
                    return;
                _F_ClickEvent=value;
                AfterSetProperty("F_ClickEvent", _F_ClickEvent);
             }
		}
	   private string _F_BindEvent;
       /// <summary>
       /// 绑定事件
       /// </summary>  
        
       public string F_BindEvent
	   { 
            get
            {
                BeforeGetProperty("F_BindEvent", _F_BindEvent);
                return _F_BindEvent;
            }
            set
            {
                if(!BeforeSetProperty("F_BindEvent", _F_BindEvent))
                    return;
                _F_BindEvent=value;
                AfterSetProperty("F_BindEvent", _F_BindEvent);
             }
		}
	   private int _F_Enable;
       /// <summary>
       /// 是否可用
       /// </summary>  
        
       public int F_Enable
	   { 
            get
            {
                BeforeGetProperty("F_Enable", _F_Enable);
                return _F_Enable;
            }
            set
            {
                if(!BeforeSetProperty("F_Enable", _F_Enable))
                    return;
                _F_Enable=value;
                AfterSetProperty("F_Enable", _F_Enable);
             }
		}
	   private int? _F_Sort;
       /// <summary>
       /// 排序
       /// </summary>  
        
       public int? F_Sort
	   { 
            get
            {
                BeforeGetProperty("F_Sort", _F_Sort);
                return _F_Sort;
            }
            set
            {
                if(!BeforeSetProperty("F_Sort", _F_Sort))
                    return;
                _F_Sort=value;
                AfterSetProperty("F_Sort", _F_Sort);
             }
		}
	  
	   private Sys_PageIndex _Sys_PageIndex ;    
       [ForeignKey("F_PageIndexF_ID")] 
       public Sys_PageIndex Sys_PageIndex
	   { 
            get
            {
                BeforeGetProperty("Sys_PageIndex",_Sys_PageIndex );
                return _Sys_PageIndex;
            }
            set
            {
                if(!BeforeSetProperty("Sys_PageIndex",_Sys_PageIndex))
                    return;
                _Sys_PageIndex=value;
                AfterSetProperty("Sys_PageIndex",_Sys_PageIndex);
            }
		}
    }
}

