//------------------------------------------------------------------------------
// <auto-generated>
//     此代码从T4模板生成。
//     黄正辉（623128629@qq.com）
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;
namespace DM.Domain
{
    /// <summary>	
    /// 数据表实体类： (sysdiagrams)
    /// </summary>
    [Serializable()]
    public partial class sysdiagrams:BaseModel
    {
	   private string _name;
       /// <summary>
       /// name
       /// </summary>  
        
       public string name
	   { 
            get
            {
                BeforeGetProperty("name", _name);
                return _name;
            }
            set
            {
                if(!BeforeSetProperty("name", _name))
                    return;
                _name=value;
                AfterSetProperty("name", _name);
             }
		}
	   private int _principal_id;
       /// <summary>
       /// principal_id
       /// </summary>  
        
       public int principal_id
	   { 
            get
            {
                BeforeGetProperty("principal_id", _principal_id);
                return _principal_id;
            }
            set
            {
                if(!BeforeSetProperty("principal_id", _principal_id))
                    return;
                _principal_id=value;
                AfterSetProperty("principal_id", _principal_id);
             }
		}
	   private int _diagram_id;
       /// <summary>
       /// diagram_id
       /// </summary>  
       [Key] [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
       public int diagram_id
	   { 
            get
            {
                BeforeGetProperty("diagram_id", _diagram_id);
                return _diagram_id;
            }
            set
            {
                if(!BeforeSetProperty("diagram_id", _diagram_id))
                    return;
                _diagram_id=value;
                AfterSetProperty("diagram_id", _diagram_id);
             }
		}
	   private int? _version;
       /// <summary>
       /// version
       /// </summary>  
        
       public int? version
	   { 
            get
            {
                BeforeGetProperty("version", _version);
                return _version;
            }
            set
            {
                if(!BeforeSetProperty("version", _version))
                    return;
                _version=value;
                AfterSetProperty("version", _version);
             }
		}
	   private Byte[] _definition;
       /// <summary>
       /// definition
       /// </summary>  
        
       public Byte[] definition
	   { 
            get
            {
                BeforeGetProperty("definition", _definition);
                return _definition;
            }
            set
            {
                if(!BeforeSetProperty("definition", _definition))
                    return;
                _definition=value;
                AfterSetProperty("definition", _definition);
             }
		}
    }
}

